FROM node:20-alpine

WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm install

# Source code will be mounted as volume
EXPOSE 8080

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
